services:

  mqtt:
    container_name: raven-eye-mqtt
    build:
      context: .
      dockerfile: ./docker/mosquitto/Dockerfile
    ports:
      - "1883:1883"
    environment:
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
    volumes:
      - ./docker/mosquitto:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  mongodb:
    container_name: raven-eye-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  fastapi:
    container_name: raven-eye-fastapi
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./app:/app
    expose:
      - "8000"
    depends_on:
      - mqtt
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: raven-eye-mediamtx
    ports:
      - "8554:8554"     # RTSP
      - "8889:8889"     # WebRTC HTTP API
      - "8189:8189/udp" # WebRTC media transport (UDP)
    environment:
      MTX_WEBRTCADDITIONALHOSTS: ${MTX_WEBRTCADDITIONALHOSTS}
    volumes:
      - ./docker/mediamtx/mediamtx.yml:/mediamtx.yml
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  frontend:
    container_name: raven-eye-frontend
    command: /run.sh
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - ./docker/frontend/run.sh:/run.sh
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"

  web:
    container_name: raven-eye-web
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/app:ro
    depends_on:
      - fastapi
      - mediamtx
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
